repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: Ruff formatter
        entry: "uv run ruff format"
        language: system
        types: [python]
        files: ^(bot|config|db|localization|scripts|services|tests)/|^main\.py$

  - repo: local
    hooks:
      - id: ruff-check
        name: Ruff linter
        entry: "uv run ruff check"
        language: system
        types: [python]
        files: ^(bot|config|db|localization|scripts|services|tests)/|^main\.py$

  - repo: local
    hooks:
      - id: isort
        name: Isort
        entry: "uv run isort"
        language: system
        types: [python]
        files: ^(bot|config|db|localization|scripts|services|tests)/|^main\.py$

  - repo: local
    hooks:
      - id: ty
        name: ty
        entry: "uv run ty check"
        language: system
        types: [python]
        files: ^(bot|config|db|localization|scripts|services|tests)/|^main\.py$

  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: "uv run pytest"
        language: system
        pass_filenames: false
        always_run: true
